baseURL = 'https://khushiramsingh680.github.io/Azure/'
languageCode = 'en-us'
title = 'Azure Cloud Documentation'
theme = 'hugo-theme-relearn'
relativeURLs = true
canonifyURLs = true
ignoreLogs = ['warning-goldmark-raw-html']
[params]
  # Relearn theme-specific parameters
  colorTheme = "light"
  layout = "wide"



